---
- name: Install docker and docker-compose on docker hosts.
  hosts: docker
  become: true
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker