---
- name: Install docker and docker-compose on docker hosts.
  hosts: docker
  become: true
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: Prep the docker hosts.
  hosts: docker
  become: true
  roles:
  - role: docker_prep
  - role: galaxy_roles/calvinbui.ansible_docker_network
